{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awilixify-example-platform
  labels:
    {{- include "awilixify-example-platform.labels" . | nindent 4 }}
  # These annotations tell the AWS controller what kind of ALB to create.
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.api | quote }}
      http:
        paths:
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders-api
                port:
                  name: http
    {{- if .Values.devtoolsUi.enabled }}
    - host: {{ .Values.ingress.hosts.devtools | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devtools-ui
                port:
                  name: http
    {{- end }}
{{- end }}
